### PR TITLE
[WIP] Bar horizontal scroll

### PR DESCRIPTION
**Pull request by clhenrick**
The bar chart needs to scroll horizontally. Solution is to have a wrapper div around the main svg element with `overflow-x: scroll` and the left axis in a separate container.

### CODE REVIEW

**Comment by clhenrick** [comment]
@biovisualize on first glance this seems to be working for horizontal scroll. Still needs some CSS touch up. Let me know if you think it's the right direction / makes sense.

**Comment by clhenrick** [comment]
@biovisualize one missing piece is setting the chart svg width based on number of bars and min & max bar width, so that it takes advantage of scrolling.

**Comment by clhenrick** [comment]
https://github.com/mapd/mapd3/pull/26/commits/12898f6ee9cbf434e47d3c3db231c248f641dfe2 is my first pass at trying to add the min bar width requirement. I'm a little hung up on how to set the chart svg width using the `xScale.domain().length * min_bar_width` though. See [this comment](https://github.com/mapd/mapd3/pull/26/commits/12898f6ee9cbf434e47d3c3db231c248f641dfe2#diff-3a414b683748c3bedf4cba86028c544aR102)

**Comment by biovisualize** [comment]
I will review and help on Monday. Looks good so far.

**Comment by clhenrick** [comment]
closing in favor of continued work in #27

**Pull request closed without merging**
